#!/bin/bash


REPO=http://coconut/shizukaze/ssh_keys.git



function sync {
  cd ~/.ssh

  mkdir -p keys

  if [ -d .repo ]; then
    cd .repo
    git remote update
    has_changes=$(git log HEAD..origin/main --oneline | cat)
    if [ -n "$has_changes" ] || [ "$1" == "-f" ]; then
      git pull
      _decrypt_keys
    else
      echo "key store up to date"
    fi
  else
    git clone $REPO .repo
    cd .repo
    _decrypt_keys
  fi
}


function _decrypt_keys {
  for key in *; do
    name=$(basename -s .gpg -a $key)
    echo $name
    gpg -d --yes -o "../keys/$name" $key 
  done
}


function add {
  key=$(readlink -f $1)
  name=$(basename -a $key)

  echo $name

  cd ~/.ssh/.repo

  gpg -c -o "$name.gpg" $key

  git add "$name.gpg"
  git commit -m "added $name.gpg"
  git push
}


$@